// src/config/api-map.ts
export const endpoints = {
  login: '/auth/login',              // POST { email|username, password }
  me: '/me',                         // GET (opcional). Si no existe, el store ya intenta /users/me
  announcements: '/announcements',   // GET ?limit=3
  scheduleToday: '/schedule/today',  // GET ?user_id=...
  scheduleSummary: '/schedule/summary/today', // GET ?user_id=...
  scheduleLast: '/schedule/last',    // GET ?user_id=...
  vehicleAssigned: '/vehicles/assigned',
  ticketsMine: '/tickets/mine'       // GET ?user_id=...
}
